<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.23">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Kara C. Hoover">

<title>Sexual Dimorphism and Biomechanical Loading in Occipital Bone Morphological Variation</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="subsistence-impacts-occipital-biomechanics_files/libs/clipboard/clipboard.min.js"></script>
<script src="subsistence-impacts-occipital-biomechanics_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="subsistence-impacts-occipital-biomechanics_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="subsistence-impacts-occipital-biomechanics_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="subsistence-impacts-occipital-biomechanics_files/libs/quarto-html/popper.min.js"></script>
<script src="subsistence-impacts-occipital-biomechanics_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="subsistence-impacts-occipital-biomechanics_files/libs/quarto-html/anchor.min.js"></script>
<link href="subsistence-impacts-occipital-biomechanics_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="subsistence-impacts-occipital-biomechanics_files/libs/quarto-html/quarto-syntax-highlighting-076ecbd647e1f0418c5051713cd9b730.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="subsistence-impacts-occipital-biomechanics_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="subsistence-impacts-occipital-biomechanics_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="subsistence-impacts-occipital-biomechanics_files/libs/bootstrap/bootstrap-547e859215a1047392d8d450828ef99e.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="eggplant quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#executive-summary" id="toc-executive-summary" class="nav-link active" data-scroll-target="#executive-summary">Executive Summary</a></li>
  <li><a href="#research-questions" id="toc-research-questions" class="nav-link" data-scroll-target="#research-questions">Research Questions</a></li>
  <li><a href="#research-answers" id="toc-research-answers" class="nav-link" data-scroll-target="#research-answers">Research Answers</a>
  <ul class="collapse">
  <li><a href="#developmental-timing-determines-biomechanical-sensitivity" id="toc-developmental-timing-determines-biomechanical-sensitivity" class="nav-link" data-scroll-target="#developmental-timing-determines-biomechanical-sensitivity">Developmental Timing Determines Biomechanical Sensitivity</a></li>
  <li><a href="#foramen-magnum-area-sex-only" id="toc-foramen-magnum-area-sex-only" class="nav-link" data-scroll-target="#foramen-magnum-area-sex-only">Foramen Magnum Area: Sex Only</a></li>
  <li><a href="#bicondylar-breadth-sex-and-subsistence-signal" id="toc-bicondylar-breadth-sex-and-subsistence-signal" class="nav-link" data-scroll-target="#bicondylar-breadth-sex-and-subsistence-signal">Bicondylar Breadth: Sex and Subsistence Signal</a></li>
  <li><a href="#lambda-inion-distance-sex-and-subsistence-signal" id="toc-lambda-inion-distance-sex-and-subsistence-signal" class="nav-link" data-scroll-target="#lambda-inion-distance-sex-and-subsistence-signal">Lambda-Inion Distance: Sex and Subsistence Signal</a></li>
  <li><a href="#occipital-form-index-and-nuchal-index-sex-only" id="toc-occipital-form-index-and-nuchal-index-sex-only" class="nav-link" data-scroll-target="#occipital-form-index-and-nuchal-index-sex-only">Occipital Form Index and Nuchal Index: Sex Only</a></li>
  <li><a href="#discriminant-function-analysis" id="toc-discriminant-function-analysis" class="nav-link" data-scroll-target="#discriminant-function-analysis">Discriminant Function Analysis</a></li>
  </ul></li>
  <li><a href="#study-design" id="toc-study-design" class="nav-link" data-scroll-target="#study-design">Study Design</a></li>
  <li><a href="#project-resources" id="toc-project-resources" class="nav-link" data-scroll-target="#project-resources">Project Resources</a></li>
  <li><a href="#tools-technologies" id="toc-tools-technologies" class="nav-link" data-scroll-target="#tools-technologies">Tools &amp; Technologies</a></li>
  <li><a href="#expertise" id="toc-expertise" class="nav-link" data-scroll-target="#expertise">Expertise</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Sexual Dimorphism and Biomechanical Loading in Occipital Bone Morphological Variation</h1>
  <div class="quarto-categories">
    <div class="quarto-category">bioarchaeology</div>
    <div class="quarto-category">skeletal biology</div>
    <div class="quarto-category">sexual dimorphism</div>
    <div class="quarto-category">biomechanics</div>
    <div class="quarto-category">ANOVA</div>
    <div class="quarto-category">discriminant function analysis</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Kara C. Hoover </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">February 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="executive-summary" class="level2">
<h2 class="anchored" data-anchor-id="executive-summary">Executive Summary</h2>
<p><strong>Problem:</strong> Occipital bone research has been biased toward evolutionary and forensic questions, often with unexplained variance. Whether behavioral differences – specifically gender-based divisions of daily activity and variation in subsistence workload – account for some of that unexplained variation is poorly understood. Distinguishing developmentally fixed traits from those subject to adult remodeling is essential for interpreting occipital morphology in both bioarchaeological and forensic contexts.</p>
<p><strong>Approach:</strong> I examined metric and nonmetric traits of the occipital bone across nine skeletal collections (n=663) representing hunter-gatherers, horticulturalists, and agriculturalists spanning Florida Archaic through 20th-century modern study collections. Two datasets were analyzed – an original Florida collection (n=98) and a mined dataset of published Plains Arikara and study collection data (n=565) – combined where variables overlapped. Two-way Type II ANOVA tested sex and subsistence as predictors for five outcome variables; discriminant function analysis evaluated foramen magnum area as a sex estimation tool.</p>
<p><strong>Insights:</strong> All five outcome variables showed significant sex-based differences. Bicondylar breadth and lambda-inion distance also varied by subsistence practice, suggesting a biomechanical signal in traits subject to adult remodeling. Foramen magnum area, fixed developmentally by age 7, showed sexual dimorphism but no subsistence signal – consistent with its canalized developmental trajectory. Discriminant function analysis using foramen magnum area achieved only 71% sex estimation accuracy, insufficient for forensic use; adding bicondylar breadth as a second predictor reduced rather than improved accuracy, indicating that biomechanical loading introduces noise into condylar metrics when used for sex estimation.</p>
<p><strong>Significance:</strong> These findings demonstrate that occipital bone traits show consistent sexual dimorphism but limited standalone forensic utility. Subsistence-based biomechanical activity contributes to variation in condylar and nuchal metrics, complicating their use as pure sex indicators. Developmentally fixed and remodeling-prone traits behave differently and should be interpreted accordingly. Larger datasets with known individual occupation data are needed to fully parse sex-based from activity-based variation in the occipital bone.</p>
<p><strong>Key Findings</strong></p>
<ul>
<li>All five outcome variables showed significant sexual dimorphism</li>
<li>Bicondylar breadth and lambda-inion distance varied significantly by subsistence practice; foramen magnum area, occipital form index, and nuchal index did not</li>
<li>Horticulturalists and hunter-gatherers both exceeded agriculturalists on bicondylar breadth; the horticulturalist vs.&nbsp;hunter-gatherer difference was negligible (Tukey HSD p=0.95)</li>
<li>Foramen magnum area achieved 71% sex estimation accuracy – above chance but below forensic standards</li>
<li>Adding bicondylar breadth as a second DFA predictor reduced accuracy to 66%, reflecting biomechanical loading as noise in condylar sex estimation</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Publication
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Hoover, K.C., &amp; Thomas, G.P.</strong> (2022). Sexual dimorphism and biomechanical loading in occipital bone morphological variation. <em>American Journal of Human Biology</em>, e23792. DOI: <a href="https://doi.org/10.1002/ajhb.23792">10.1002/ajhb.23792</a></p>
</div>
</div>
<hr>
</section>
<section id="research-questions" class="level2">
<h2 class="anchored" data-anchor-id="research-questions">Research Questions</h2>
<ol type="1">
<li>Does foramen magnum area vary by biological sex and/or subsistence practice?</li>
<li>Does bicondylar breadth vary by sex and/or subsistence?</li>
<li>Do ectocranial traits (lambda-inion distance, occipital form index, nuchal index) vary by sex and/or subsistence?</li>
<li>How accurately can foramen magnum area predict biological sex, alone and combined with bicondylar breadth?</li>
</ol>
<hr>
</section>
<section id="research-answers" class="level2">
<h2 class="anchored" data-anchor-id="research-answers">Research Answers</h2>
<section id="developmental-timing-determines-biomechanical-sensitivity" class="level3">
<h3 class="anchored" data-anchor-id="developmental-timing-determines-biomechanical-sensitivity">Developmental Timing Determines Biomechanical Sensitivity</h3>
<p>Traits fixed early in development and under stronger genetic control (foramen magnum length and breadth) behave differently from traits influenced by muscle use and adult remodeling (bicondylar breadth, lambda-inion distance, external occipital protuberance depth, nuchal crest presence, nuchal line count, general EOP form). This distinction structured both the predictions and the results. Full two-way ANOVA results for all five outcome variables are in the table below; individual results are discussed in the subsections that follow.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Variable</th>
<th>Dataset</th>
<th>Predictor</th>
<th>F</th>
<th>p</th>
<th>Sig.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Foramen Magnum Area</td>
<td>Original</td>
<td>Subsistence</td>
<td>0.00</td>
<td>.952</td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>Sex</td>
<td>9.27</td>
<td>.003</td>
<td>**</td>
</tr>
<tr class="odd">
<td>Foramen Magnum Area</td>
<td>Combined*</td>
<td>Subsistence</td>
<td>2.41</td>
<td>.090</td>
<td>.</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>Sex</td>
<td>129.26</td>
<td>&lt;.002</td>
<td>***</td>
</tr>
<tr class="odd">
<td>Bicondylar Breadth</td>
<td>Original</td>
<td>Subsistence</td>
<td>9.93</td>
<td>.003</td>
<td>**</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>Sex</td>
<td>14.12</td>
<td>&lt;.002</td>
<td>***</td>
</tr>
<tr class="odd">
<td>Bicondylar Breadth</td>
<td>Combined</td>
<td>Subsistence</td>
<td>19.6</td>
<td>&lt;.002</td>
<td>***</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>Sex</td>
<td>70.9</td>
<td>&lt;.002</td>
<td>***</td>
</tr>
<tr class="odd">
<td>Lambda-Inion</td>
<td>Original</td>
<td>Subsistence</td>
<td>5.95</td>
<td>.017</td>
<td>*</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>Sex</td>
<td>11.93</td>
<td>.001</td>
<td>***</td>
</tr>
<tr class="odd">
<td>Occipital Form Index</td>
<td>Original*</td>
<td>Subsistence</td>
<td>0.18</td>
<td>.670</td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>Sex</td>
<td>29.66</td>
<td>&lt;.002</td>
<td>***</td>
</tr>
<tr class="odd">
<td>Nuchal Index</td>
<td>Original</td>
<td>Subsistence</td>
<td>0.73</td>
<td>.390</td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>Sex</td>
<td>23.18</td>
<td>&lt;.002</td>
<td>***</td>
</tr>
</tbody>
</table>
<p>Type II SS two-way ANOVA results. * white.adjust = TRUE used for heteroscedastic models. Significance: . p &lt; .10 | * p &lt; .05 | ** p &lt; .01 | *** p &lt; .001</p>
</section>
<section id="foramen-magnum-area-sex-only" class="level3">
<h3 class="anchored" data-anchor-id="foramen-magnum-area-sex-only">Foramen Magnum Area: Sex Only</h3>
<p>The basicranium is fully developed by age 7 and the foramen magnum does not remodel in adulthood, so any sex-based variation in this region reflects early developmental trajectory rather than biomechanical activity. Foramen magnum area was significantly different between the sexes in both datasets (Original: F=9.27, p=.003; Combined: F=129.26, p&lt;.002), with males averaging approximately 10 cm<sup>2</sup> larger in the combined dataset. No subsistence effect emerged in either dataset (Original: F=0.00, p=.952; Combined: F=2.41, p=.09), consistent with developmental canalization. Panel A shows the sex difference clearly; panel B shows the absence of subsistence-based separation.</p>
<p><strong>Figure 1A–B. Foramen magnum area by sex (A) and subsistence (B). Significant sex dimorphism; no subsistence effect.</strong></p>
<p><img src="revised-plot-fm.png" class="img-fluid"></p>
<p><strong>Interpretation:</strong> Foramen magnum area is sexually dimorphic but subsistence-blind – exactly what developmental canalization predicts. Its utility in sex estimation is real but limited; the overlap between distributions means it cannot classify sex reliably on its own.</p>
<p>The bivariate relationship between foramen magnum sagittal (FMS) and transverse (FMT) dimensions – the raw measurements combined into the area index – shows the same pattern. Despite statistically significant dimorphism, the D statistic of 0.92 by sex reflects substantial distributional overlap. By subsistence the overlap is even greater (D=0.37), with the three groups nearly indistinguishable.</p>
<p><strong>Figure 2. Foramen magnum dimensions (FMS × FMT) by sex. D=0.92; substantial overlap despite significant dimorphism.</strong></p>
<p><img src="revised-scatter-fm-sex.png" class="img-fluid"></p>
<p><strong>Interpretation:</strong> The marginal density plots make the overlap visible in a way that mean differences alone do not. Even the largest standardized difference in this dataset (D=0.92 by sex) leaves the distributions substantially overlapping – the core problem for forensic sex estimation from this trait.</p>
<p><strong>Figure 3. Foramen magnum dimensions (FMS × FMT) by subsistence. D=0.37; groups are largely indistinguishable.</strong></p>
<p><img src="revised-scatter-fm-subsistence.png" class="img-fluid"></p>
<p><strong>Interpretation:</strong> Three subsistence groups with very different activity profiles produce nearly identical foramen magnum dimension distributions. This is the clearest evidence that this trait is not responding to biomechanical loading.</p>
</section>
<section id="bicondylar-breadth-sex-and-subsistence-signal" class="level3">
<h3 class="anchored" data-anchor-id="bicondylar-breadth-sex-and-subsistence-signal">Bicondylar Breadth: Sex and Subsistence Signal</h3>
<p>Unlike the foramen magnum, the occipital condyles articulate with the first cervical vertebra and may remodel under biomechanical pressure from head rotation, flexion, and extension across the lifespan. Bicondylar breadth was significantly different by both sex and subsistence in both datasets (see ANOVA table above). Sex effects were robust (Original: F=14.12, p&lt;.002; Combined: F=70.9, p&lt;.002). Subsistence effects were also significant (Original: F=9.93, p=.003; Combined: F=19.6, p&lt;.002). Post-hoc Tukey HSD on the combined dataset confirmed horticulturalists and hunter-gatherers both exceeded agriculturalists in condylar breadth; the horticulturalist vs.&nbsp;hunter-gatherer difference was negligible (p=.95), suggesting a threshold effect rather than a linear gradient across subsistence intensity.</p>
<p><strong>Figure 4A–B. Bicondylar breadth by sex (A) and subsistence (B). Significant effects for both predictors.</strong></p>
<p><img src="revised-plot-bcb.png" class="img-fluid"></p>
<p><strong>Interpretation:</strong> The subsistence signal in bicondylar breadth – absent in foramen magnum area – is consistent with biomechanical remodeling of the condylar region. Populations with more physically demanding and gender-differentiated subsistence strategies show broader condylar breadths, suggesting activity-based variation alongside sexual dimorphism.</p>
</section>
<section id="lambda-inion-distance-sex-and-subsistence-signal" class="level3">
<h3 class="anchored" data-anchor-id="lambda-inion-distance-sex-and-subsistence-signal">Lambda-Inion Distance: Sex and Subsistence Signal</h3>
<p>Lambda-inion distance measures the length of the nuchal plane from the meeting of the sagittal and lambdoid sutures to the external occipital protuberance. This region serves as the attachment site for the nuchal ligament, which supports the weight of the head and may develop in response to sustained physical activity. Males averaged approximately 4.8 mm longer than females (F=11.93, p=.001). Controlling for sex, subsistence was also significant (F=5.95, p=.017), with hunter-gatherers averaging approximately 3.5 mm longer than agriculturalists. Lambda-inion distance may partly reflect EOP morphology – more robust protuberances alter the nuchal plane – but the subsistence signal is consistent with the biomechanical interpretation.</p>
<p><strong>Figure 5A–B. Lambda-inion distance by sex (A) and subsistence (B). Plot p-values are unadjusted one-way comparisons; see ANOVA table above for two-way model result.</strong></p>
<p><img src="revised-plot-li.png" class="img-fluid"></p>
<p><strong>Interpretation:</strong> Lambda-inion distance is the only ectocranial metric that shows both a sex effect and a subsistence effect, making it the strongest candidate for activity-based variation in the posterior occipital region. The hunter-gatherer advantage is consistent with more physically intensive and biomechanically demanding activity patterns.</p>
</section>
<section id="occipital-form-index-and-nuchal-index-sex-only" class="level3">
<h3 class="anchored" data-anchor-id="occipital-form-index-and-nuchal-index-sex-only">Occipital Form Index and Nuchal Index: Sex Only</h3>
<p>The ectocranial posterior of the occipital bone – the region of heavy buttressing and muscle attachment for neck and head movement – showed sexual dimorphism across both composite indexes but no subsistence-based variation. The Occipital Form Index (EOP depth + general form) was significantly higher in males (F=29.66, p&lt;.002), reflecting deeper protuberances. The Nuchal Index (nuchal line count + nuchal crest presence) was also significantly higher in males (F=23.18, p&lt;.002), reflecting greater muscle marking. Neither index differed significantly by subsistence (Form Index: p=.670; Nuchal Index: p=.390).</p>
<p><strong>Figure 6A–B. Occipital form index by sex (A) and subsistence (B). Sex effect only.</strong></p>
<p><img src="revised-plot-form.png" class="img-fluid"></p>
<p><strong>Interpretation:</strong> The absence of a subsistence signal in the occipital form index is somewhat unexpected given the attachment of neck muscles used in physically demanding activities. The result may reflect the composite nature of the index – combining a continuous metric (EOP depth) with a nominal trait (general form) may obscure subsistence-related variation in either component.</p>
<p><strong>Figure 7A–B. Nuchal index by sex (A) and subsistence (B). Sex effect only.</strong></p>
<p><img src="revised-plot-nuchal.png" class="img-fluid"></p>
<p><strong>Interpretation:</strong> Nuchal muscle marking is clearly sexually dimorphic but insensitive to subsistence practice in these datasets. The result is consistent with the form index finding and may reflect the broad occupational heterogeneity within the agricultural group – modern study collections and 19th-century military remains represent diverse activity profiles that may wash out any subsistence signal.</p>
</section>
<section id="discriminant-function-analysis" class="level3">
<h3 class="anchored" data-anchor-id="discriminant-function-analysis">Discriminant Function Analysis</h3>
<p>Given the significant sexual dimorphism in foramen magnum area, we tested its utility for sex estimation using discriminant function analysis on the combined dataset (n=663). Data were scaled and split 70/30 into training and test sets. Foramen magnum area alone predicted biological sex at 71% accuracy (LDA coefficient=1.108) – above chance but well below the threshold for forensic utility. Adding bicondylar breadth as a second predictor reduced accuracy to 66%, with coefficients of 0.89 and 0.41 respectively. The decline in accuracy when adding bicondylar breadth is consistent with biomechanical loading introducing noise into condylar-based sex estimation – the subsistence signal in bicondylar breadth that makes it biologically interesting is precisely what undermines its forensic utility.</p>
<hr>
</section>
</section>
<section id="study-design" class="level2">
<h2 class="anchored" data-anchor-id="study-design">Study Design</h2>
<p><strong>Data Source:</strong> Two skeletal datasets collected and mined by the authors. Original dataset (n=98): Florida skeletal collections including Windover (8BR246), Hutchinson Island (8MT37), FSU Teaching Collection, and St.&nbsp;Mark’s Military (8WA108). Mined dataset (n=565): published thesis data on Plains Arikara (Larson 39WW2, Leavenworth 39CO9, Mobridge 39WW1) and large modern study collections (Hamann-Todd, Terry Collection).</p>
<p><strong>Data Handling:</strong> Three measurement trials for five metric traits using an electronic sliding caliper; two observation trials for three nonmetric traits. Intra-observer agreement confirmed via kappa (irr). Measurement error assessed via Levene’s test across trials (all &lt;0.51% of trait variance). Foramen magnum length and breadth combined as an ellipse area index (pi x L x B). PCA on five ectocranial variables identified three vector clusters supporting two composite indexes: Occipital Form Index (EOP depth + general form) and Nuchal Index (nuchal crest + nuchal line count). Datasets combined where variables overlapped (foramen magnum area and bicondylar breadth) to create combined dataset (n=663).</p>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Site / Collection</th>
<th>Dataset</th>
<th>Subsistence</th>
<th>Date Range</th>
<th>n</th>
<th>F</th>
<th>M</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Windover (8BR246)</td>
<td>Original</td>
<td>Hunter-Gatherer</td>
<td>8522–7421 BP</td>
<td>47</td>
<td>24</td>
<td>23</td>
</tr>
<tr class="even">
<td>Hutchinson Island (8MT37)</td>
<td>Original</td>
<td>Hunter-Gatherer</td>
<td>2000–1000 BP</td>
<td>16</td>
<td>8</td>
<td>8</td>
</tr>
<tr class="odd">
<td>FSU Teaching Collection</td>
<td>Original</td>
<td>Agriculture</td>
<td>20th century</td>
<td>22</td>
<td>11</td>
<td>11</td>
</tr>
<tr class="even">
<td>St.&nbsp;Mark’s Military (8WA108)</td>
<td>Original</td>
<td>Agriculture</td>
<td>19th century</td>
<td>13</td>
<td>0</td>
<td>13</td>
</tr>
<tr class="odd">
<td>Larson (39WW2)</td>
<td>Mined</td>
<td>Horticultural</td>
<td>1679–1733</td>
<td>115</td>
<td>57</td>
<td>58</td>
</tr>
<tr class="even">
<td>Leavenworth (39CO9)</td>
<td>Mined</td>
<td>Horticultural</td>
<td>1802–1832</td>
<td>30</td>
<td>14</td>
<td>16</td>
</tr>
<tr class="odd">
<td>Mobridge (39WW1)</td>
<td>Mined</td>
<td>Horticultural</td>
<td>1600–1700</td>
<td>56</td>
<td>31</td>
<td>25</td>
</tr>
<tr class="even">
<td>Hamann-Todd Collection</td>
<td>Mined</td>
<td>Agriculture</td>
<td>1912–1938</td>
<td>107</td>
<td>54</td>
<td>53</td>
</tr>
<tr class="odd">
<td>Terry Collection</td>
<td>Mined</td>
<td>Agriculture</td>
<td>1899–1941</td>
<td>257</td>
<td>129</td>
<td>128</td>
</tr>
</tbody>
</table>
<p>Table 1. Sample composition by site, dataset, subsistence category, and sex.</p>
<p><strong>Analytical Approach:</strong></p>
<ol type="1">
<li>Intraobserver error – kappa2 and Spearman correlation for nonmetric traits; Levene’s test across measurement trials for metric traits</li>
<li>PCA on five ectocranial variables to identify variable clusters and support index construction</li>
<li>Assumption testing – normality (QQ plots), homogeneity of variance (Levene’s test), outliers (Rosner test) for original and combined datasets</li>
<li>Two-way ANOVA (Type II SS, car::Anova) with sex and subsistence as predictors, preceded by interaction testing (Type III); no interactions detected; heteroscedasticity-corrected models (white.adjust=TRUE) used for Index_Form (original) and Index_FM (combined)</li>
<li>Post-hoc Tukey HSD for combined dataset subsistence comparisons on bicondylar breadth and foramen magnum area</li>
<li>Discriminant function analysis (MASS::lda) for sex estimation using foramen magnum area alone and with bicondylar breadth as a second predictor; 70/30 train/test split</li>
</ol>
<hr>
</section>
<section id="project-resources" class="level2">
<h2 class="anchored" data-anchor-id="project-resources">Project Resources</h2>
<p><strong>Repository:</strong> <a href="https://github.com/kchoover14/subsistence-impacts-occipital-biomechanics">github.com/kchoover14/subsistence-impacts-occipital-biomechanics</a></p>
<p><strong>Data:</strong> Original skeletal data collected by the authors from Florida collections; mined data from published theses on Plains Arikara and modern study collections. All data files included in repository.</p>
<ul>
<li><code>data-occ-original-raw-22dec21.csv</code> – raw original Florida dataset (3 measurement trials)</li>
<li><code>data-occ-westcott-raw.csv</code>, <code>data-occ-williams-raw.csv</code> – raw mined thesis datasets</li>
<li><code>data-occ-mined.csv</code> – cleaned mined dataset</li>
<li><code>revised-preparation-original.csv</code>, <code>revised-preparation-mined.csv</code>, <code>revised-preparation-combined.csv</code> – analysis-ready datasets</li>
</ul>
<p><strong>Code:</strong></p>
<ul>
<li><code>revised-preparation-original.R</code> – wrangling, reliability testing, measurement error, PCA, index creation for original Florida dataset</li>
<li><code>revised-preparation-mined.R</code> – standardization and merging of mined Arikara and study collection data</li>
<li><code>revised-exploratory.R</code> – assumption testing (normality, Levene’s, outliers) for original and combined datasets</li>
<li><code>revised-analysis.R</code> – two-way ANOVA, Tukey HSD, discriminant function analysis, and all figures</li>
</ul>
<p><strong>Project Artifacts:</strong></p>
<ul>
<li>ANOVA figures (n=5): <code>revised-plot-fm.png</code>, <code>revised-plot-bcb.png</code>, <code>revised-plot-li.png</code>, <code>revised-plot-form.png</code>, <code>revised-plot-nuchal.png</code></li>
<li>FM dimension scatter figures (n=2): <code>revised-scatter-fm-sex.png</code>, <code>revised-scatter-fm-subsistence.png</code></li>
<li>PCA biplot (n=1): <code>revised-pca-biplot.png</code></li>
</ul>
<p><strong>Environment:</strong></p>
<ul>
<li><code>renv.lock</code> and <code>renv/</code> – restore with <code>renv::restore()</code></li>
</ul>
<p><strong>License:</strong></p>
<ul>
<li>Code and scripts © Kara C. Hoover, licensed under the <a href="LICENSE">MIT License</a>.</li>
<li>Data, figures, and written content © Kara C. Hoover, licensed under <a href="https://creativecommons.org/licenses/by-nc-nd/4.0/">CC BY-NC-ND 4.0</a>.</li>
</ul>
<hr>
</section>
<section id="tools-technologies" class="level2">
<h2 class="anchored" data-anchor-id="tools-technologies">Tools &amp; Technologies</h2>
<p><strong>Languages:</strong> R</p>
<p><strong>Tools:</strong> None</p>
<p><strong>Packages:</strong> dplyr | tidyr | irr | car | psych | EnvStats | MASS | factoextra | ggplot2 | cowplot</p>
<hr>
</section>
<section id="expertise" class="level2">
<h2 class="anchored" data-anchor-id="expertise">Expertise</h2>
<p><strong>Domain Expertise:</strong> bioarchaeology | skeletal biology | sexual dimorphism | biomechanics | intraobserver reliability | measurement error | PCA | discriminant function analysis | mixed datasets</p>
<p><strong>Transferable Expertise:</strong> Combining original data collection with published data mining to expand analytical scope while maintaining methodological rigor; applying multiple statistical frameworks to distinguish genetic from behavioral sources of skeletal variation; evaluating the forensic utility and limitations of morphological metrics.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>